name: Release Please

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  release-please:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    outputs:
      release_created:  ${{ steps.release.outputs.release_created }}
      release_tag:  ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: googleapis/release-please-action@16a9c90856f42705d54a6fda1823352bdc62cf38  # v4.4.0
        id: release

  create-release:
    permissions:
      contents: write
    needs: release-please
    if: ${{ needs.release-please.outputs.release_created }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8  # v6.0.1
        with:
          persist-credentials: false

      - name: Setup Ninja
        run: sudo apt-get install ninja-build

      - name: Build singleheader
        run: |
          cmake -DMERVE_TESTING=OFF -G Ninja -B build
          cmake --build build --target merve-singleheader-lib

      - name: Create singleheader.zip
        run: |
          cd build/singleheader
          zip singleheader.zip merve.h merve.cpp
          mv singleheader.zip ../../singleheader/
          cp merve.h merve.cpp ../../singleheader/

      - name: Create release
        run: gh release upload "$RELEASE_TAG" singleheader/*
        env:
          GH_TOKEN: ${{ github.token }}
          RELEASE_TAG: ${{ needs.release-please.outputs.release_tag }}
